import type { Metadata } from "next";
import { Inter, Rubik } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import {TanstackProvider} from '@/app/providers/TanstackProvider'

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Diablo II Resurrected - The Holy Grail",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={rubik.className}>
     <TanstackProvider>
        <Header />
        {children}
        </TanstackProvider>
      </body>
    </html>
  );
}
